color0 #263021
color1 #fd4663
color2 #9bc18b
color3 #7ab886
color4 #7ab8a5
color5 #b7d3ac
color6 #acd3b3
color7 #f2f3f2
color8 #646e5e
color9 #fd4663
color10 #9bc18b
color11 #7ab886
color12 #7ab8a5
color13 #b7d3ac
color14 #acd3b3
color15 #f2f3f2

cursor                #f2f3f2
cursor_text_color     #1d231a
background            #1d231a
foreground            #f2f3f2
selection_foreground  #b1b6af
selection_background  #263021
active_border_color   #9bc18b
inactive_border_color #263021
url_color             #9bc18b

active_tab_foreground   #1d221b
active_tab_background   #9bc18b
inactive_tab_foreground #b1b6af
inactive_tab_background #263021
cursor_trail_color      #b1b6af
