color0 #212930
color1 #fd4663
color2 #80a8cc
color3 #7c7eca
color4 #a17ec8
color5 #a4c1da
color6 #a4a6da
color7 #f2f2f3
color8 #616a71
color9 #fd4663
color10 #80a8cc
color11 #7c7eca
color12 #a17ec8
color13 #a4c1da
color14 #a4a6da
color15 #f2f2f3

cursor                #f2f2f3
cursor_text_color     #1a1f23
background            #1a1f23
foreground            #f2f2f3
selection_foreground  #afb3b6
selection_background  #212930
active_border_color   #80a8cc
inactive_border_color #212930
url_color             #80a8cc

active_tab_foreground   #1b1f22
active_tab_background   #80a8cc
inactive_tab_foreground #afb3b6
inactive_tab_background #212930
cursor_trail_color      #afb3b6
