cursor #f1dedc
cursor_text_color #d8c2be

foreground            #f1dedc
background            #1a1110
selection_foreground  #000000
selection_background  #f28b82
url_color             #f44336

color0   #1a1110
color1   #ff2624
color2   #5ef436
color3   #ffd524
color4   #f8341d
color5   #700700
color6   #f44336
color7   #ffe8e7
color8   #9e8d8c
color9   #ff6b6a
color10  #91ff74
color11  #ffe474
color12  #ff6156
color13  #ff7d74
color14  #ffaba5
color15  #fff5f5
