color0 #302921
color1 #fd4663
color2 #c1a78b
color3 #b1b280
color4 #98b280
color5 #d3c0ac
color6 #cfd0af
color7 #f3f2f2
color8 #706960
color9 #fd4663
color10 #c1a78b
color11 #b1b280
color12 #98b280
color13 #d3c0ac
color14 #cfd0af
color15 #f3f2f2

cursor                #f3f2f2
cursor_text_color     #231f1a
background            #231f1a
foreground            #f3f2f2
selection_foreground  #b6b3af
selection_background  #302921
active_border_color   #c1a78b
inactive_border_color #302921
url_color             #c1a78b

active_tab_foreground   #221f1b
active_tab_background   #c1a78b
inactive_tab_foreground #b6b3af
inactive_tab_background #302921
cursor_trail_color      #b6b3af
