background #0f1416
foreground #dee3e5

cursor #84d2e7
selection_background #004e5c
selection_foreground #acedff

color0 #1b2022
color1 #ffb4ab
color2 #84d2e7
color3 #bfc4eb
color4 #b2cbd2
color5 #004e5c
color6 #334a51
color7 #dee3e5

color8 #252b2d
color9 #ffb4ab
color10 #84d2e7
color11 #bfc4eb
color12 #b2cbd2
color13 #004e5c
color14 #334a51
color15 #dee3e5
