config_version = 12

[backdrop]
blur_intensity = 0.54999998770654202

[bar.default]
background_opacity = 0.57999998703598976
center = [ "clock", "spacer_3", "weather" ]
contact_shadow = true
end = [ "media", "tray", "notifications", "volume", "session" ]
margin_edge = 5
margin_ends = 10
margin_opposite_edge = 1
padding = 23
start = [ "workspaces", "spacer_2", "audio_visualizer" ]
thickness = 30

[control_center]
hidden_tabs = [ "power", "bluetooth" ]

[location]
auto_locate = true

[lockscreen_widgets]
enabled = false
schema_version = 2
widget_order = [ "lockscreen-login-box@DP-1" ]

    [lockscreen_widgets.grid]
    cell_size = 16
    major_interval = 4
    visible = true

    [lockscreen_widgets.widget."lockscreen-login-box@DP-1"]
    box_height = 196.0
    box_width = 810.0
    cx = 960.0
    cy = 898.0
    output = "DP-1"
    rotation = 0.0
    type = "login_box"

        [lockscreen_widgets.widget."lockscreen-login-box@DP-1".settings]
        background_color = "surface_variant"
        background_opacity = 0.88
        background_radius = 12.0
        center_password_text = false
        input_opacity = 1.0
        input_radius = 6.0
        layout = "regular"
        show_caps_lock = true
        show_keyboard_layout = true
        show_login_button = true
        show_media = true
        show_session_buttons = true
        show_unlock_hint = true
        show_weather = true

[shell]
polkit_agent = true
show_location = false

    [shell.panel]
    floating_layer = "top"
    open_near_click_control_center = true
    transparency_mode = "glass"

    [shell.screen_corners]
    size = 100

    [shell.shadow]
    direction = "center"

[theme]
builtin = "Catppuccin"
community_palette = "ADW"
mode = "auto"
source = "wallpaper"
wallpaper_scheme = "soft"

    [theme.templates]
    builtin_ids = [ "gtk3", "gtk4", "kitty", "niri", "qt", "starship" ]
    community_ids = [ "zed" ]

[wallpaper]
directory = "~/.config/wallpapers"

    [wallpaper.default]
    path = "/home/feel/.config/wallpapers/wallhaven-21oqrg.jpg"

    [wallpaper.last]
    path = "/home/feel/.config/wallpapers/wallhaven-21oqrg.jpg"

    [wallpaper.monitors.DP-1]
    path = "/home/feel/.config/wallpapers/wallhaven-21oqrg.jpg"

[widget.audio_visualizer]
bands = 80
capsule = true
interactive = false
mirrored = false
width = 120

[widget.clock]
format = "{:%B %d, %A %H:%M}"
scale = 0.90000000000000013

[widget.launcher]
capsule = true
glyph = "add"

[widget.media]
album_art_only = true
hide_when_no_media = true
scale = 1.3500000000000001

[widget.spacer_2]
length = 30
type = "spacer"

[widget.spacer_3]
type = "spacer"

[widget.tray]
drawer = true
scale = 1.3

[widget.wallpaper]
enabled = false

[widget.weather]
scale = 0.75
show_condition = false

[widget.workspaces]
active_pill_size = 1.55
hide_when_empty = true
inactive_pill_size = 0.80000000000000004
pill_scale = 0.70000000000000007
show_labels = false