config_version = 12

[backdrop]
blur_intensity = 0.54999998770654202

[bar]
order = [ "default" ]

    [bar.default]
    background_opacity = 0.57999998703598976
    center = [ "clock", "spacer_3", "weather" ]
    contact_shadow = true
    end = [ "media", "tray", "notifications", "volume", "session" ]
    margin_edge = 5
    margin_ends = 10
    margin_opposite_edge = 1
    padding = 23
    start = [ "workspaces" ]
    thickness = 24

[control_center]
hidden_tabs = [ "power", "bluetooth" ]

    [control_center.calendar]
    show_events_card = false

[desktop_widgets]
schema_version = 2
widget_order = [
    "desktop-widget-0000000000000001",
    "desktop-widget-0000000000000002",
    "desktop-widget-0000000000000004",
    "desktop-widget-0000000000000005"
]

    [desktop_widgets.grid]
    cell_size = 8
    major_interval = 4
    visible = true

    [desktop_widgets.widget.desktop-widget-0000000000000001]
    box_height = 0.0
    box_width = 0.0
    cx = 1808.0
    cy = 927.5
    output = "DP-1"
    rotation = 0.0
    type = "media_player"

        [desktop_widgets.widget.desktop-widget-0000000000000001.settings]
        background_padding = 24
        hide_when_no_media = true
        layout = "vertical"

    [desktop_widgets.widget.desktop-widget-0000000000000002]
    box_height = 120.0
    box_width = 112.0
    cx = 1808.0
    cy = 881.0
    output = "DP-1"
    rotation = 0.0
    type = "fancy_audio_visualizer"

        [desktop_widgets.widget.desktop-widget-0000000000000002.settings]
        background = false
        fade_when_idle = true
        visualization_mode = "wave"

    [desktop_widgets.widget.desktop-widget-0000000000000004]
    box_height = 0.0
    box_width = 0.0
    cx = 64.0
    cy = 897.5
    output = "DP-1"
    rotation = 0.0
    type = "sysmon"

        [desktop_widgets.widget.desktop-widget-0000000000000004.settings]
        background = true
        display = "gauge"
        gauge_layout = "horizontal"
        shadow = true
        stat = "cpu_temp"
        stat2 = "cpu_usage"

    [desktop_widgets.widget.desktop-widget-0000000000000005]
    box_height = 0.0
    box_width = 0.0
    cx = 124.0
    cy = 993.0
    output = "DP-1"
    rotation = 0.0
    type = "weather"

        [desktop_widgets.widget.desktop-widget-0000000000000005.settings]
        background = true
        font_family = "JetBrains Mono NL"
        forecast_days = 2
        show_forecast = true

[location]
auto_locate = true

[lockscreen_widgets]
enabled = false
schema_version = 2
widget_order = [ "lockscreen-login-box@DP-1" ]

    [lockscreen_widgets.grid]
    cell_size = 16
    major_interval = 4
    visible = true

    [lockscreen_widgets.widget."lockscreen-login-box@DP-1"]
    box_height = 196.0
    box_width = 810.0
    cx = 960.0
    cy = 898.0
    output = "DP-1"
    rotation = 0.0
    type = "login_box"

        [lockscreen_widgets.widget."lockscreen-login-box@DP-1".settings]
        background_color = "surface_variant"
        background_opacity = 0.88
        background_radius = 12.0
        center_password_text = false
        input_opacity = 1.0
        input_radius = 6.0
        layout = "regular"
        show_caps_lock = true
        show_keyboard_layout = true
        show_login_button = true
        show_media = true
        show_session_buttons = true
        show_unlock_hint = true
        show_weather = true

[notification]
background_opacity = 0.86999998055398464
history_retention_hours = 1
layer = "overlay"
scale = 0.85000000521540642

[plugin_settings."kenn/keybind-cheatsheet"]
compositor = "niri"

[plugins]
enabled = [ "nightwatch75/todo" ]

[shell]
polkit_agent = true
show_location = false

    [shell.panel]
    floating_layer = "top"
    open_near_click_control_center = true
    transparency_mode = "glass"

    [shell.shadow]
    direction = "center"

[theme]
builtin = "Catppuccin"
community_palette = "ADW"
source = "wallpaper"
wallpaper_scheme = "soft"

    [theme.templates]
    builtin_ids = [ "gtk3", "gtk4", "kitty", "niri", "qt", "starship" ]
    community_ids = [ "spicetify", "zed", "vicinae", "yazi" ]

[wallpaper]
directory = "~/.config/wallpapers"

    [wallpaper.default]
    path = "/home/feel/.config/wallpapers/wallhaven-d83g9m.jpg"

    [wallpaper.last]
    path = "/home/feel/.config/wallpapers/wallhaven-d83g9m.jpg"

    [wallpaper.monitors.DP-1]
    path = "/home/feel/.config/wallpapers/wallhaven-d83g9m.jpg"

[widget.audio_visualizer]
bands = 80
capsule = true
interactive = false
mirrored = false
width = 120

[widget.clock]
format = "{:%B %d, %A %H:%M}"
scale = 0.90000000000000013

[widget.launcher]
capsule = true
glyph = "add"

[widget.media]
album_art_only = true
hide_when_no_media = true
scale = 1.3500000000000001

[widget.spacer_3]
type = "spacer"

[widget.tray]
drawer = true
scale = 1.3

[widget.wallpaper]
enabled = false

[widget.weather]
scale = 0.75
show_condition = false

[widget.workspaces]
active_pill_size = 1.55
anchor = true
inactive_pill_size = 0.80000000000000004
pill_scale = 0.70000000000000007
show_labels = false